# Change these first
owner: Coinection # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Coinection
    url: https://coinection.eu

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status.coinection.eu
  #theme: light
  themeUrl: https://status.coinection.eu/coinection.css
  baseUrl: /uptime
  logoUrl: https://coinection.eu/logo.svg
  name: Coinection
  introTitle: "**Coinection**"
  introMessage: This page contains the status page of the [Coinection](https://coinection.eu) platform.
  navbar:
    - title: Status
      href: /
    - title: View website
      href: https://coinection.eu

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
